# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  # I'm leaving this here for next time, since it comes up so rarely
  # that I always have to look it up. If we fork something and want to
  # include our fork (the same applies to anything not in the forge), we
  # add it to our fixtures under `repositories` instead of under
  # `forge_modules`. Also, we add it to the Puppetfile in the control
  # repo; not to metadata.json in nebula.
  #
  #repositories:
  #  module_name:
  #    repo: "https://github.com/mlibrary/repo_name"
  repositories:
    apache:
      repo: "https://github.com/mlibrary/puppetlabs-apache"
  forge_modules:
    rbenv:               {"repo": "jdowning/rbenv",             "ref": "3.0.0" }
    archive:             {"repo": "puppet/archive",             "ref": "7.1.0" }
    kmod:                {"repo": "puppet/kmod",                "ref": "4.0.1" }
    letsencrypt:         {"repo": "puppet/letsencrypt",         "ref": "10.1.0"} # breaking change, not clear if this is safe to update
    logrotate:           {"repo": "puppet/logrotate",           "ref": "7.0.2" }
    nginx:               {"repo": "puppet/nginx",               "ref": "5.0.0" }
    php:                 {"repo": "puppet/php",                 "ref": "9.0.0" }
    unattended_upgrades: {"repo": "puppet/unattended_upgrades", "ref": "8.1.0" }
    apt:                 {"repo": "puppetlabs/apt",             "ref": "9.0.2" } # 9.1.0+ needs updated stdlib
    augeas_core:         {"repo": "puppetlabs/augeas_core",     "ref": "1.5.0" }
    concat:              {"repo": "puppetlabs/concat",          "ref": "7.4.0" }
    cron_core:           {"repo": "puppetlabs/cron_core",       "ref": "1.3.0" }
    docker:              {"repo": "puppetlabs/docker",          "ref": "7.0.0" } # 8.0.0+ needs updated stdlib
    firewall:            {"repo": "puppetlabs/firewall",        "ref": "5.0.0" }
    host_core:           {"repo": "puppetlabs/host_core",       "ref": "1.3.0" }
    inifile:             {"repo": "puppetlabs/inifile",         "ref": "6.1.1" }
    lvm:                 {"repo": "puppetlabs/lvm",             "ref": "2.1.0" }
    mount_core:          {"repo": "puppetlabs/mount_core",      "ref": "1.3.0" }
    mysql:               {"repo": "puppetlabs/mysql",           "ref": "14.0.0"} # 15.0.0 needs updated stdlib
    ntp:                 {"repo": "puppetlabs/ntp",             "ref": "10.1.0"}
    reboot:              {"repo": "puppetlabs/reboot",          "ref": "5.0.0" }
    sshkeys_core:        {"repo": "puppetlabs/sshkeys_core",    "ref": "2.5.0" }
    stdlib:              {"repo": "puppetlabs/stdlib",          "ref": "8.6.0" } # update this when moving to newer version of firewall
    debconf:             {"repo": "stm/debconf",                "ref": "6.0.0" }
    #postgresql:   {"repo": "puppetlabs/postgresql",   "ref": "8.3.0"}
    #puppetdb:     {"repo": "puppetlabs/puppetdb",     "ref": "7.13.0"}
