# This file can be used to install module depdencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  # I'm leaving this here for next time, since it comes up so rarely
  # that I always have to look it up. If we fork something and want to
  # include our fork (the same applies to anything not in the forge), we
  # add it to our fixtures under `repositories` instead of under
  # `forge_modules`. Also, we add it to the Puppetfile in the control
  # repo; not to metadata.json in nebula.
  #
  #repositories:
  #  module_name:
  #    repo: "git://github.com/mlibrary/repo_name"
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.2.0"
    apache:
      repo: "puppetlabs/apache"
      ref: "5.4.0"
    apt:
      repo: "puppetlabs/apt"
      ref: "7.3.0"
    archive:
      repo: "puppet/archive"
      ref: "4.4.0"
    concat:
      repo: "puppetlabs/concat"
      ref: "6.2.0"
    docker:
      repo: "puppetlabs/docker"
      ref: "3.4.0"
    firewall:
      repo: "puppetlabs/firewall"
      ref: "2.2.0"
    inifile:
      repo: "puppetlabs/inifile"
      ref: "4.1.0"
    lvm:
      repo: "puppetlabs/lvm"
      ref: "1.0.1"
    mysql:
      repo: "puppetlabs/mysql"
      ref: "10.3.0"
    ntp:
      repo: "puppetlabs/ntp"
      ref: "8.2.0"
    postgresql:
      repo: "puppetlabs/postgresql"
      ref: "6.3.0"
    puppetdb:
      repo: "puppetlabs/puppetdb"
      ref: "7.4.0"
    reboot:
      repo: "puppetlabs/reboot"
      ref: "2.0.0"
    logrotate:
      repo: "puppet/logrotate"
      ref: "4.0.0"
    letsencrypt:
      repo: "puppet/letsencrypt"
      ref: "5.0.0"
    nginx:
      repo: "puppet/nginx"
      ref: "1.0.0"
    php:
      repo: "puppet/php"
      ref: "7.0.0"
    debconf:
      repo: "stm/debconf"
      ref: "3.0.0"
    kmod:
      repo: "camptocamp/kmod"
      ref: "2.1.0"
    rbenv:
      repo: "jdowning/rbenv"
      ref: "2.2.0"
    resolv_conf:
      repo: "saz/resolv_conf"
      ref: "4.1.0"
    ec2tagfacts:
      repo: "bryana/ec2tagfacts"
      ref: "0.3.0"
    java:
      repo: "puppetlabs/java"
      ref: "6.0.0"
    java_ks:
      repo: "puppetlabs/java_ks"
      ref: "3.1.0"
    confluence:
      repo: "puppet/confluence"
      ref: "3.2.0"
    jira:
      repo: "puppet/jira"
      ref: "4.0.0"
