---
.gitignore:
  required:
    - ---.git/ # No .gitignore needs this
    - ---/doc/ # We have files here
    - /.pdkignore
    - /.tmp/
    - /.tool-versions
    - /Puppetfile.lock
    - /modules/
    - /spec/examples.txt
Gemfile:
  required:
    ':development':
      - gem: faker
      - gem: librarian-puppet
        version: '>= 5.0'
      - gem: pdk
        version: '>= 3.3.0'
      - gem: standard
      # Silence bundler errors. It's expected that newer PDK will
      # add syslog. When that happens, remove this line.
      - gem: syslog
Rakefile:
  extra_disabled_lint_checks:
    # We sometimes refer to non-nebula puppet fileserver paths.
    # This check will make breaking changes on lint_fix task.
    - puppet_url_without_modules
    # likes to add useless indents in heredocs and never pass its own tests
    - strict_indent
    # likes to crash when "fixing" files
    - trailing_comma
spec/default_facts.yml:
  extra_facts:
    ec2_tag_role: nebula::role::aws
    datacenter: mydatacenter
    installed_backports: []
    letsencrypt_directory:
      foo.example.com: /etc/letsencrypt/live/foo.example.com
      example.invalid: /etc/letsencrypt/live/example.invalid
    prometheus_errors_total: 0
    # The ruby tests by default are set to install 2.4.3 and 2.5.0, so 2.4.2
    # represents an installed but not desired version of ruby, while 2.5.0
    # represents an already-installed and still desired version of ruby.
    ruby_versions:
      - 2.4.2
      - 2.5.0
    vm_guests:
      - invalid_existing_guest
spec/spec_helper.rb:
  spec_overrides:
    - "module DefaultHieraConfig"
    - "  extend RSpec::SharedContext"
    - "  let(:hiera_config) { 'spec/fixtures/hiera/default_config.yaml' }"
    - "end"
    - ""
    - "RSpec.configure do |c|"
    - "  c.default_facts = default_facts"
    - "  c.include DefaultHieraConfig"
    - "end " # trailing space prevents PDK from skipping this line
