services:
  specs:
    build: .
    command: 'bundle exec rake spec'
    volumes:
      - .:/app

  spec_prep:
    build: .
    command: 'bundle exec rake fixtures:prep'
    volumes:
      - .:/app

  lint:
    build: .
    command:
    - /bin/bash
    - '-c'
    - 'bundle exec rake syntax lint && bundle exec rake metadata_lint; bundle exec rake standard'
    volumes:
      - .:/app
