version: '3'
services:
  specs:
    build: .
    command: 'bundle exec rake spec'
    volumes:
      - .:/app
      - ./vendor:/gems

  spec_prep:
    build: .
    command: 'bundle exec rake spec_prep'
    volumes:
      - .:/app
      - ./vendor:/gems

  lint:
    build: .
    command:
    - /bin/bash
    - '-c'
    - 'bundle exec rake rubocop && bundle exec rake syntax lint && bundle exec rake metadata_lint'
    volumes:
      - .:/app
