version: '3'
services:
  specs:
    build: .

  lint:
    build: .
    command:
    - /bin/bash
    - '-c'
    - 'bundle exec rake rubocop && bundle exec rake syntax lint && bundle exec rake metadata_lint'
