version: '3'
services:
  specs:
    build: .
    command: 'bundle exec rake parallel_spec'

  lint:
    build: .
    command:
    - /bin/bash
    - '-c'
    - 'bundle exec rake rubocop && bundle exec rake syntax lint && bundle exec rake metadata_lint'

  librarian:
    build: .
    command: 'bundle exec rake librarian'
