# Copyright (c) 2020 The Regents of the University of Michigan.
# All Rights Reserved. Licensed according to the terms of the Revised
# BSD License. See LICENSE.txt for details.

# nebula::profile::networking::firewall::http
#
# Manage firewall (iptables) settings for HTTP/s
#
# This class gathers all firewall rules with the tag 'haproxy'
# to allow access from any haproxy servers. The actual rules are 
# first generated by nebula::profile::haproxy each time
# a role (e.g. load_balancer) includes the haproxy profile.
#
# @example
#   include nebula::profile::networking::firewall::http
class nebula::profile::networking::firewall::http () {
  Firewall <<| tag == 'haproxy' |>>
}


