# Copyright (c) 2019 The Regents of the University of Michigan.
# All Rights Reserved. Licensed according to the terms of the Revised
# BSD License. See LICENSE.txt for details.

# nebula::profile::hathitrust::ingest_jobs
#
# Manage the ingest systemd service for hathitrust
#
# @example
#   include nebula::profile::hathitrust::ingest_jobs
class nebula::profile::hathitrust::ingest_jobs(
  String $config,
  String $feed_home,
  String $stats_home,
  String $recipient,
  String $rights_db_config,
  String $rights_log = '/tmp/populate_rights.log'
) {

  package { 'heirloom-mailx': }

  $feed_perl = "/usr/bin/perl -I ${feed_home}/lib"
  $feed_jobs = "${feed_home}/bin/jobs"
  $feed_daily = "${feed_jobs}/feed.daily"
  $feed_log  = "${feed_home}/var/log"
  $base_env = [
    "MAILTO=${recipient}",
    "FEED_HOME=${feed_home}"
  ]


  cron {
    default:
      environment => $base_env + [ "HTFEED_CONFIG=${config}" ],
      user        => 'libadm';

    ## HOURLY  JOBS

    # pick up rights generated by CRMS and the bib rights algorithm and load them into the database
    'rights load':
      ensure  => 'absent';

    # Queue volumes for conversion on GRIN and check their statuses
    'GRIN conversion / status check':
      ensure  =>  'absent';

    ## DAILY JOBS

    # mail previous days' rights load summary
    'mail rights load summary':
      ensure => 'absent';

    # summary of previous day's ingest activity
    'ingest summary':
      ensure  =>  'absent';

    # run daily tasks: update grin, get bibrecords, queue new material, deposit rights
    'daily tasks':
      ensure  => 'absent';

    # copy crms renewals from latte-1
    'crms renewals':
      ensure  =>  'absent';

    'copy google rejects list':
      ensure      => 'absent';

    ## WEEKLY JOBS

    'get brittle books data':
      ensure => 'absent';

    'generate ingest logs':
      ensure =>  'absent';

    'generate ingest reports':
      ensure  => 'absent';

    'repository statistics':
      ensure => 'absent';

    'audit statistics':
      ensure => 'absent';

    ## MONTHLY JOBS
    ########## MONTHLY ############

    # Set volumes that are VIEW_FULL on GRIN but ic or und in the rights DB to
    # pdus/gfv, and reset volumes that are pdus/gfv but not VIEW_FULL on GRIN to
    # their bib-determined rights

    'grin reports':
      ensure   => 'absent';

    'grin gfv':
      ensure   => 'absent';

    'all sources':
      ensure =>  'absent';

    'generate dpla log':
      command  => "/bin/bash ${stats_home}/bin/generate_dpla_log.sh",
      monthday => 1,
      hour     => 2,
      minute   => 35;

    'monthly ingest count':
      ensure   => 'absent';

    'copyright distribution snapshot':
      ensure   => 'absent';

    'full zephir comparison':
      command  => "${feed_perl} ${feed_jobs}/feed.monthly/zephir_diff.pl",
      monthday => 1,
      hour     => 4,
      minute   => 0;

  }


}
