name: Run CI

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Clone latest repository
      uses: actions/checkout@v2
    - name: Run tests
      run: |
        docker run `docker build -q .` bundle exec rake rubocop
        docker run `docker build -q .` bundle exec rake syntax lint
        docker run `docker build -q .` bundle exec rake metadata_lint
        docker run `docker build -q .` bundle exec rake spec
