name: Run CI

on:
  push:
    branches: [$default-branch]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
        - "lint"
        - "specs"
    steps:
    - uses: actions/checkout@v6
    - name: Run tests
      run: |
        docker compose --file docker-compose.test.yml build
        docker compose --file docker-compose.test.yml run ${{ matrix.target }}
