name: Run CI

on:
  push:
    branches:
    - production
  pull_request:

jobs:
  setup_tests:
    name: _setup
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.define_matrix.outputs.os }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: cache fixtures
      uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      id: cache-fixtures
      with:
        path: spec/fixtures/modules
        key: cache-fixtures-modules-${{ hashFiles('.fixtures.yml') }}
    - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
      with:
        bundler-cache: true
    - name: Define test matrix
      id: define_matrix
      run: bundle exec rake supported_os >> "$GITHUB_OUTPUT"
    - if: ${{ steps.cache-fixtures.outputs.cache-hit != 'true' }}
      name: rake fixtures:prep
      run: bundle exec rake fixtures:prep
  lint:
    name: "All OSes: lint"
    needs: setup_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
      with:
        bundler-cache: true
    - name: lint with Standard Ruby style guide
      run: bundle exec standardrb
    - name: check Puppet syntax
      run: bundle exec rake syntax
    - name: Run puppet-lint
      run: bundle exec rake lint
    - name: lint metadata.json
      run: bundle exec rake metadata_lint
  spec:
    name: "${{ matrix.os }}"
    needs: setup_tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.setup_tests.outputs.os) }}
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@319994f95fa847cf3fb3cd3dbe89f6dcde9f178f # v1.295.0
      with:
        bundler-cache: true
    - name: Restore fixtures cache
      uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
      with:
        path: spec/fixtures/modules
        key: cache-fixtures-modules-${{ hashFiles('.fixtures.yml') }}
    - name: rake fixtures:prep
      run: bundle exec rake fixtures:prep
    - name: "Run SUPPORTED_OS=\"${{ matrix.os }}\" rake ci:spec"
      env:
        SUPPORTED_OS: ${{ matrix.os }}
      run: bundle exec rake ci:spec
