name: Check Dependencies

on:
  push:
    branches:
    - production
  pull_request:
    paths:
    - metadata.json

jobs:
  librarian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
      with:
        bundler-cache: true
    - name: Resolve dependencies with librarian-puppet
      run: bundle exec librarian-puppet install --verbose
