name: Run CI

on:
  push:
    branches: [$default-branch]
  pull_request:
    paths:
      - metadata.json

jobs:
  librarian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Resolve Dependencies
      run: |
        docker compose --file docker-compose.test.yml build
        docker compose --file docker-compose.test.yml run librarian
