name: Check Dependencies

on:
  push:
    branches:
    - production
  pull_request:
    paths:
    - metadata.json

jobs:
  librarian:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: ruby/setup-ruby@e65c17d16e57e481586a6a5a0282698790062f92 # v1.300.0
      with:
        bundler-cache: true
    - name: Resolve dependencies with librarian-puppet
      run: bundle exec librarian-puppet install --verbose
